/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalassignemnt;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class CarRegister extends javax.swing.JFrame {
    Object[] row = new Object[5];
    

    /**
     * Creates new form CarRegister
     */
    public CarRegister() {
        initComponents();
        String filepath = "D:\\My APU stuff\\Year 2 APU sem 1\\assignment\\OODJ\\CarRentalAssignemnt\\CarRentalAssignemnt\\CarRegister.txt";
        File f = new File(filepath);
        try{
            BufferedReader br = new BufferedReader(new FileReader(f));
            DefaultTableModel model = (DefaultTableModel)cartable.getModel();
            
            
            Object[] tableLines = br.lines().toArray();
            for(int i = 0; i< tableLines.length; i++){
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(":");
                model.addRow(dataRow);
            }
        }catch(Exception ex){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        carnumber = new javax.swing.JTextField();
        brandtxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartable = new javax.swing.JTable();
        statustxt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("BN Machine", 0, 36)); // NOI18N
        jLabel1.setText("CAR REGISTER");

        jLabel2.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        jLabel2.setText("Car Reg No");

        jLabel4.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        jLabel4.setText("Brand");

        jLabel5.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        jLabel5.setText("Status");

        jLabel6.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        jLabel6.setText("Price");

        Save.setBackground(new java.awt.Color(153, 255, 153));
        Save.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Edit.setBackground(new java.awt.Color(153, 255, 153));
        Edit.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(153, 255, 153));
        Delete.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(153, 255, 153));
        Back.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        carnumber.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N

        brandtxt.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N

        pricetxt.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N

        cartable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg No", "Brand", "Status", "Price"
            }
        ));
        cartable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cartableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(cartable);

        statustxt.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        statustxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Booked" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(carnumber)
                                    .addComponent(brandtxt)
                                    .addComponent(statustxt, 0, 173, Short.MAX_VALUE)
                                    .addComponent(pricetxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Back)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Save)
                                        .addGap(18, 18, 18)
                                        .addComponent(Edit)))
                                .addGap(18, 18, 18)
                                .addComponent(Delete)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(carnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(brandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(statustxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Edit)
                    .addComponent(Delete))
                .addGap(18, 18, 18)
                .addComponent(Back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
        String carNum,brand, status = null, price;
        carNum = carnumber.getText();
        brand = brandtxt.getText();
        if(statustxt.getSelectedItem() == "Available"){
            status = "Available";
        }
        else if(statustxt.getSelectedItem() == "Booked"){
            status = "Booked";
        }
        price = pricetxt.getText();
        if(carNum.equals("") || brand.equals("") || status.equals("") || price.equals("")){
            JOptionPane.showMessageDialog(this,"please fill all the detail");
                setVisible(false);
                dispose();
                new CarRegister().setVisible(true);
        }              
        else{
            RegisterCar reg = new RegisterCar(carNum,brand,status,price);
        if(reg.verifyCarReg()== true){
            JOptionPane.showMessageDialog(null, "Register Successful");
                    setVisible(false);
                    dispose();
                    new CarRegister().setVisible(true);
        }
    }//GEN-LAST:event_SaveActionPerformed
    
    row[0] = carNum;
    row[1] = brand;
    row[2] = status;
    row[3] = price;
    DefaultTableModel model = (DefaultTableModel)cartable.getModel();
    model.addRow(row);
    
}
    private void cartableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartableMouseReleased
        // TODO add your handling code here:
        int selectedRow = cartable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)cartable.getModel();
        carnumber.setText(model.getValueAt(selectedRow, 0).toString());
        brandtxt.setText(model.getValueAt(selectedRow, 1).toString());
        statustxt.setSelectedItem(model.getValueAt(selectedRow, 2).toString());
        pricetxt.setText(model.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_cartableMouseReleased

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        String NumCar, Brand, Status = null, Price;
        NumCar = carnumber.getText();
        Brand = brandtxt.getText();
        if(statustxt.getSelectedItem() == "Available"){
            Status = "Available";
        }
        else if(statustxt.getSelectedItem() == "Booked"){
            Status = "Booked";
        }
        Price = pricetxt.getText();
        int i = cartable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)cartable.getModel();
        if(i>= 0){
            model.setValueAt(carnumber.getText(), i, 0);
            model.setValueAt(brandtxt.getText(), i, 1);
            model.setValueAt(statustxt.getSelectedItem(), i, 2);
            model.setValueAt(pricetxt.getText(), i, 3);
        EditCar reg = new EditCar(NumCar,Brand,Status,Price);
        if(reg.editCar()== true){
            JOptionPane.showMessageDialog(null, "Register Successful");
                    setVisible(false);
                    dispose();
                    new CarRegister().setVisible(true);
        }    
        }
        else{
            JOptionPane.showMessageDialog(null, "Error");
        }
        
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tmodel = (DefaultTableModel) cartable.getModel();     
        if(cartable.getSelectedRowCount()==1){
            tmodel.removeRow(cartable.getSelectedRow());
        }
        else{
            JOptionPane.showMessageDialog(this,"please select row");
        }
        String filePath = "D:\\My APU stuff\\Year 2 APU sem 1\\assignment\\OODJ\\CarRentalAssignemnt\\CarRentalAssignemnt\\CarRegister.txt";
        File file = new File(filePath);
        try
        {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0;i<cartable.getRowCount();i++)
            {
                for(int j=0;j<cartable.getColumnCount();j++)
                {
                    bw.write(cartable.getValueAt(i,j).toString()+":");
                }
                bw.newLine(); 
            }
            JOptionPane.showMessageDialog(null, "Data Deleted");
            
            bw.close();
            fw.close();
        }       
        catch (IOException ex)
        {
            
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HomePageAdmin().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Save;
    private javax.swing.JTextField brandtxt;
    private javax.swing.JTextField carnumber;
    private javax.swing.JTable cartable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JComboBox<String> statustxt;
    // End of variables declaration//GEN-END:variables
}
