/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalassignemnt;

/**
 *
 * @author HP
 */
public class HomePageAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HomePageAdmin
     */
    public HomePageAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regcarmenu = new javax.swing.JButton();
        historymenu = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        regadminmenu = new javax.swing.JButton();
        managebooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("BN Machine", 0, 36)); // NOI18N
        jLabel1.setText("WELCOME ADMIN");

        regcarmenu.setBackground(new java.awt.Color(153, 255, 153));
        regcarmenu.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        regcarmenu.setText("Register Car");
        regcarmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regcarmenuActionPerformed(evt);
            }
        });

        historymenu.setBackground(new java.awt.Color(153, 255, 153));
        historymenu.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        historymenu.setText(" History Report");
        historymenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historymenuActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(153, 255, 153));
        logout.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        regadminmenu.setBackground(new java.awt.Color(153, 255, 153));
        regadminmenu.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        regadminmenu.setText("Register Admin");
        regadminmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regadminmenuActionPerformed(evt);
            }
        });

        managebooking.setBackground(new java.awt.Color(153, 255, 153));
        managebooking.setFont(new java.awt.Font("BN Machine", 0, 12)); // NOI18N
        managebooking.setText("Manage Booking");
        managebooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managebookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(historymenu)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(regadminmenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(managebooking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regcarmenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(regcarmenu)
                .addGap(12, 12, 12)
                .addComponent(managebooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regadminmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(historymenu)
                .addGap(8, 8, 8)
                .addComponent(logout)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regcarmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regcarmenuActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CarRegister().setVisible(true);
    }//GEN-LAST:event_regcarmenuActionPerformed

    private void regadminmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regadminmenuActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new RegisterAdmin().setVisible(true);
    }//GEN-LAST:event_regadminmenuActionPerformed

    private void historymenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historymenuActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HistoryReport().setVisible(true);
    }//GEN-LAST:event_historymenuActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Role().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void managebookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managebookingActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ManageBooking().setVisible(true);
    }//GEN-LAST:event_managebookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton historymenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton managebooking;
    private javax.swing.JButton regadminmenu;
    private javax.swing.JButton regcarmenu;
    // End of variables declaration//GEN-END:variables
}
